config/routes.rb
Rails.application.routes.draw do

  # Definimos la ruta para ingresar un nuevo libro
  get '/books/new' => 'books#new'
  post 'books' => 'books#create'

  # Definimos la ruta para ver el listado de los prestamos
  get '/books/prestamos' => 'books#prestamos'


  # Definimos la ruta para ingresar un nuevo usuario
  get '/users/new' => 'users#new'
  post 'users' => 'users#create'

  # Definimos la ruta para editar y actualizar la informacion de los libros
  get '/books/:id/prestar' => 'books#prestar', as: :prestar_book
  patch '/books/:id'  => 'books#update'

  # Definimos la ruta para eliminar un usuario
  delete 'users/:id' => 'users#destroy', as: :destroy_user

  delete 'books/:id' => 'books#destroy', as: :destroy_book

  # Definimos la ruta para ver todos los usuarios
  get '/users' => 'users#index'

  # Definimos la ruta para ver todos los libros
  get '/books' => 'books#index'

  # Definimos la ruta para ver un libro en especifico
  get '/books/:id' => 'books#show', as: :book

  # Definimos la ruta para editar y actualizar la informacion de los libros
  get '/books/:id/edit' => 'books#edit', as: :edit_book
  patch '/books/:id' => 'books#update'

  # Definimos la ruta para ver un usuario en especifico
  get '/users/:id' => 'users#show', as: :user

  # Definimos la ruta para editar y actualizar la informacion de un usuario
  get '/users/:id/edit' => 'users#edit', as: :edit_user
  patch '/users/:id' => 'users#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # cada libro pertenece a un usuario
  belongs_to :user

  validates :nombre, :autor,:presence => true

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


end

app/models/user.rb
class User < ApplicationRecord
  # Un usuario tiene multiples libros
  has_many :books

  validates :nombres, :apellidos, :cedula, :presence => true

  validates :email,
            :presence => true,
            :uniqueness =>  {:message => "Esta cuenta de correo ya se encuentra registrada!"},
            :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def array_user
    @users = User.all
    @users_id_name2 = Array.new()
    @users.each do |u|
      arraT = Array.new()
      @users_id_name2.push(arraT.push(u.nombres.capitalize! + " "+ u.apellidos.capitalize!, u.id))
    end

    return @users_id_name2
  end


  # Aqui ingresamos los registros de los nuevos libros
  def new
    @book = Book.new
    @users_id_name  = array_user
  end

  # Aqui vemos todos los libros
  def index
    @books = Book.all
  end

  # Aqui vemos cada libro por individual
  def show
    @book = Book.find(params[:id])
  end

  def prestar
    @book = Book.find(params[:id])
    @users_id_name  = array_user
  end

  def prestamos
    @books = Book.all
  end

  # Aqui editamos cada uno de los libros
  def edit
    @book = Book.find(params[:id])
    @users_id_name  = array_user
  end

  # Aqui actualizamos cada uno de los libros editados
  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      redirect_to(:action => 'index', :id => @book.id)
    else
      render 'edit'
    end
  end

  # Aqui creamos un nuevo libro
  def create
    @book = Book.new(book_new_params)
    if @book.save
      redirect_to '/books'
    else
      render 'new'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to '/books'

  end


  private
  def book_new_params
    params.require(:book).permit(:nombre, :autor, :descripcion, :image, :user_id)
  end

  # tomamos los objetos del metodo libro los cuales vamos a editar
  private
  def book_params
    params.require(:book).permit(:nombre, :autor ,:descripcion,:user_id)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # aqui vemos todos los usuarios
  def index
    @users = User.all
  end
  # Aqui ingresamos los registros de los nuevos libros
  def new
    @user = User.new
  end

  # Aqui vemos cada usuario por individual
  def show
    @user = User.find(params[:id])
  end

  # Aqui editamos cada uno de los usuarios
  def edit
    @user = User.find(params[:id])
  end

  # Aqui actualizamos cada uno de los libros editados
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to(:action => 'index', :id => @user.id)
    else
      render 'edit'
    end
  end

  # Aqui creamos un nuevo usuario
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to '/users'
    else
      flash.now[:alert] = @user.errors[:email].first
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to '/users'

  end

  # tomamos los objetos del metodo libro los cuales vamos a editar
  private
  def user_params
    params.require(:user).permit(:nombres, :apellidos ,:cedula, :email)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="row justify-content-center">
  <div class="column col-sm-8 ">
  <%= form_for(@book) do |f| %>
        <br>

        <div class="form-group">
          <%= f.label :nombre %><br>
          <%= f.text_area :nombre,:class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :autor%><br>
          <%= f.text_area :autor, :class => "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :descripcion %><br>
          <%= f.text_area :descripcion, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update", :class => "btn btn-success" %>
        </div>
  <% end %>
</div>
</div>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

<div class="row justify-content-center">
<% @books.each do |b| %>

      <div class="col-sm-4">

        <div class="card" style="width: 20rem;" >
          <%=  image_tag b.image.url(:medium) ,:class =>"card-img-top" %>
          <div class="card-block">
            <h4><%= b.nombre.downcase.capitalize! %></h4>
            <h7> <%= b.autor.capitalize! %></h7>
            <p> <%= b.descripcion %> </p>
            <%= link_to "See more", book_path(b), :class => "btn btn-primary"%>
            <%= link_to "Prestar", prestar_book_path(b), :class => "btn btn-warning "%>
          </div>

        </div>
        <br>
      </div>

<% end %>
</div>

app/views/books/new.html.erb
<%= form_for(@book) do |b| %>
    <div class="row justify-content-center">
      <div class="column col-sm-8 ">
        <br>
        <div class="form-group">
          <%= b.label :nombre %><br>
          <%= b.text_field :nombre,:class => "form-control" %>
        </div>
        <div class="form-group">
          <%= b.label :autor%><br>
          <%= b.text_field :autor, :class => "form-control"%>
        </div>
        <div class="form-group">
          <%= b.label :descripcion %><br>
          <%= b.text_area :descripcion, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= b.label :image %><br>
          <%= b.file_field :image , :class => "form-control-file"%>
        </div>
        <div class="form-group">
          <%= b.label :usuario %><br>
          <%= b.select(:user_id,options_for_select(@users_id_name)) %>
        </div>

        <div class="actions">
          <%= b.submit "Create", :class => "btn btn-primary" %>
        </div>
      </div>
    </div>


<% end %>

app/views/books/prestamos.html.erb
<table class="table table-inverse">
  <thead>
  <tr>
    <th>#</th>
    <th>Nombre</th>
    <th>Autor</th>
    <th>Prestado a</th>
    <th>Regresar</th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |b| %>
    <% if b.user_id !=  1 %>
      <tr>
        <th scope="row"> <%= b.id %> </th>
        <td> <%= b.nombre %> </td>
        <td> <%= b.autor %> </td>
        <td> <%= b.user[:nombres] %> <%= b.user[:apellidos] %>  </td>
        <td> <%= link_to "Devolver", prestar_book_path(b) %> </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/books/prestar.html.erb
<div class="row justify-content-center">
  <div class="column col-sm-8 ">
    <%= form_for(@book) do |f| %>
        <br>

        <div class="form-group">
          <%= f.label :nombre %><br>
          <%= f.text_field :nombre,:class => "form-control",:readonly => true %>
        </div>
        <div class="form-group">
          <%= f.label :autor%><br>
          <%= f.text_field :autor, :class => "form-control",:readonly => true%>
        </div>
        <div class="form-group">
          <%= f.label :descripcion %><br>
          <%= f.text_area :descripcion, :class => "form-control",:readonly => true %>
        </div>
        <div class="form-group">
          <%= f.label :usuario %><br>
          <%= f.select(:user_id,options_for_select(@users_id_name), :class => "form-control") %>
        </div>
        <div class="form-group">
          <%= f.submit "Prestar", :class => "btn btn-success" %>
        </div>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class="row justify-content-center">
  <%=  image_tag @book.image.url(:medium) %>
  <div class="column col-sm-8 ">


  <h1><%= @book.nombre %></h1>
  <h7><%= @book.autor %></h7>
  <%= @book.descripcion %>

  <%= link_to "Edit", edit_book_path(@book), :class => "button"%>
    <%= link_to "Delete", destroy_book_path(@book), :method => :delete, :data => { :confirm => 'Estas seguro?' },:class => "btn btn-danger" %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%=  stylesheet_link_tag    "application" %>
    <%=  javascript_include_tag "application", 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>



  </head>

  <body>

  <div class="container">
      <br>
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">Personal library</a>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active ">
              <a class="nav-link btn btn-outline-success my-2 my-sm-0" href="/users">Usuarios <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/users/new">New user</a>
            </li>
            <li class="nav-item active">
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle btn btn-outline-success my-2 my-sm-0" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Libros
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="/books">Todos</a>
                <a class="dropdown-item" href="/books/prestamos">Prestamos</a>
                <a class="dropdown-item" href="/books/new">Nuevo libro</a>
              </div>
            </li>

          </ul>
        </div>
      </nav>
      <br>


    <%= yield %>
  </div>


  </body>
</html>

app/views/users/edit.html.erb
<%= form_for(@user) do |us| %>
    <div class="row justify-content-center">
      <div class="column col-sm-6 ">
        <br>
        <div class="form-group">
          <%= us.label :nombres %>
          <%= us.text_field :nombres ,:class => "form-control"  %>
        </div>
        <div class="form-group">
          <%= us.label :apellidos %>
          <%= us.text_field :apellidos ,:class => "form-control"  %>
        </div>
        <div class="form-group">
          <%= us.label :cedula %>
          <%= us.text_field :cedula ,:class => "form-control"  %>
        </div>
        <div class="form-group">
          <%= us.label :email %>
          <%= us.text_field :email ,:class => "form-control"  %>
        </div>

        <div class="actions">
          <%= us.submit "Update", :class => "btn btn-primary" %>
        </div>
      </div>
    </div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<table class="table table-inverse">
  <thead>
  <tr>
    <th>#</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Username</th>
    <th>Email</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <% if user.id != 1%>
      <tr>
        <th scope="row"> <%= user.id %> </th>
        <td> <%= user.nombres %> </td>
        <td> <%= user.apellidos %> </td>
        <td> <%= user.cedula %> </td>
        <td> <%= user.email %> </td>
        <td>
          <%= link_to "View",user_path(user),:class => "btn btn-info"%>
          <%= link_to "Edit",edit_user_path(user),:class => "btn btn-primary"%>
          <%= link_to "Delete", destroy_user_path(user), :method => :delete, :data => { :confirm => 'Estas seguro?' },:class => "btn btn-danger" %>
        <td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<%= form_for(@user) do |us| %>
    <div class="row justify-content-center">
      <div class="column col-sm-6 ">
        <br>
        <div class="form-group">
          <%= us.label :nombres %>
          <%= us.text_field :nombres ,:class => "form-control"  %>
        </div>
        <div class="form-group">
          <%= us.label :apellidos %>
          <%= us.text_field :apellidos ,:class => "form-control"  %>
        </div>
        <div class="form-group">
          <%= us.label :cedula %>
          <%= us.text_field :cedula ,:class => "form-control"  %>
        </div>
        <div class="form-group">
          <%= us.label :email %>
          <% if flash[:alert] %>
              <div class="alert alert-danger">
                <%= flash[:alert] %>
              </div>
          <% end %>
          <%= us.text_field :email.downcase ,:class => "form-control"  %>
        </div>

        <div class="actions">
          <%= us.submit "Create", :class => "btn btn-primary" %>
        </div>
      </div>
    </div>


<% end %>

app/views/users/show.html.erb
<div>
  <h1><%= @user.nombres %></h1>
  <h7><%= @user.apellidos %></h7>
  <%= @user.cedula %>

  <%= link_to "Edit", edit_user_path(@user)%>
</div>